fix(profiling): ensure max_stack_events as an int (#3751)
While enabling the profiler for Lambda functions, I ran into this issue:

```
Exception in thread ddtrace.profiling.collector.stack:StackCollector:
Traceback (most recent call last):
File "/var/lang/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/var/task/ddtrace/internal/periodic.py", line 70, in run
self._target()
File "/var/task/ddtrace/profiling/collector/__init__.py", line 43, in periodic
self.recorder.push_events(events)
File "/var/task/ddtrace/profiling/recorder.py", line 76, in push_events
q = self.events[event_type]
File "/var/task/ddtrace/profiling/recorder.py", line 21, in __missing__
v = self[key] = self.default_factory(key)
File "/var/task/ddtrace/profiling/recorder.py", line 80, in _get_deque_for_event_type
return collections.deque(maxlen=self.max_events.get(event_type, self.default_max_events))
TypeError: an integer is required
```

Co-authored-by: Brett Langdon <brett.langdon@datadoghq.com>
Co-authored-by: Kyle Verhoog <kyle@verhoog.ca>