ci(celery): wait 500ms before attempting to flush async spans (#5177)
`tests.contrib.celery.test_integration.CeleryIntegrationTask:test_concurrent_delays`
should wait some time (500ms works locally) before attempting to flush
spans generated by async tasks. This should hopefully make this test
less flaky.

```
assert 199 == 200
 +  where 199 = len([[<Span(id=15545269754856869115,trace_id=15302847542956879948,parent_id=None,name=celery.apply)>], [<Span(id=556290242...=celery.apply)>], [<Span(id=12550604606658276739,trace_id=7059575862388011681,parent_id=None,name=celery.apply)>], ...])
self = <tests.contrib.celery.test_integration.CeleryIntegrationTask testMethod=test_concurrent_delays>

    def test_concurrent_delays(self):
        # it should create one trace for each delayed execution
        @self.app.task
        def fn_task():
            return 42
    
        results = [fn_task.delay() for _ in range(100)]
    
        for result in results:
            assert result.get(timeout=self.ASYNC_GET_TIMEOUT) == 42
    
        traces = self.pop_traces()
>       assert len(traces) == (200 if self.ASYNC_USE_CELERY_FIXTURES else 100)
E       assert 199 == 200
E        +  where 199 = len([[<Span(id=15545269754856869115,trace_id=15302847542956879948,parent_id=None,name=celery.apply)>], [<Span(id=556290242...=celery.apply)>], [<Span(id=12550604606658276739,trace_id=7059575862388011681,parent_id=None,name=celery.apply)>], ...])

tests/contrib/celery/test_integration.py:42: AssertionError
```

[Sample
failure](https://app.circleci.com/pipelines/gh/DataDog/dd-trace-py/29113/workflows/b8f0da12-5bd9-4189-aeb1-913b92f06cfd/jobs/1979229)

## Checklist

- [x] Change(s) are motivated and described in the PR description.
- [x] Testing strategy is described if automated tests are not included
in the PR.
- [x] Risk is outlined (performance impact, potential for breakage,
maintainability, etc).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] [Library release note
guidelines](https://ddtrace.readthedocs.io/en/stable/contributing.html#Release-Note-Guidelines)
are followed.
- [x] Documentation is included (in-code, generated user docs, [public
corp docs](https://github.com/DataDog/documentation/)).
- [x] Author is aware of the performance implications of this PR as
reported in the benchmarks PR comment.

## Reviewer Checklist

- [x] Title is accurate.
- [x] No unnecessary changes are introduced.
- [x] Description motivates each change.
- [x] Avoids breaking
[API](https://ddtrace.readthedocs.io/en/stable/versioning.html#interfaces)
changes unless absolutely necessary.
- [x] Testing strategy adequately addresses listed risk(s).
- [x] Change is maintainable (easy to change, telemetry, documentation).
- [x] Release note makes sense to a user of the library.
- [x] Reviewer is aware of, and discussed the performance implications
of this PR as reported in the benchmarks PR comment.